<a href="https://colab.research.google.com/github/Joeaviator/POKEMON_PREPROCESSIG/blob/main/POKEMON_PREPROCESSING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
from google.colab import files
file = files.upload()

Saving pokemon_data.csv to pokemon_data.csv

In [7]:
df=pd.read_csv('pokemon_data.csv')
df.head()

   Unnamed: 0  against_water  attack  ... weight_kg generation  is_legendary
0           0            0.5      49  ...       6.9          1             0
1           1            0.5      62  ...      13.0          1             0
2           2            0.5     100  ...     100.0          1             0
3           5            2.0     104  ...      90.5          1             0
4          11            1.0      45  ...      32.0          1             0

[5 rows x 14 columns]

In [4]:
df.isnull().sum()

Unnamed: 0       0
against_water    0
attack           0
capture_rate     0
classfication    0
defense          0
sp_attack        0
sp_defense       0
speed            0
type1            0
type2            0
weight_kg        0
generation       0
is_legendary     0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     398 non-null    int64
 1   against_water  398 non-null    float64
 2   attack         398 non-null    int64
 3   capture_rate   398 non-null    object
 4   classfication  398 non-null    object
 5   defense        398 non-null    int64
 6   sp_attack      398 non-null    int64
 7   sp_defense     398 non-null    int64
 8   speed          398 non-null    int64
 9   type1          398 non-null    object
 10  type2          398 non-null    object
 11  weight_kg      398 non-null    float64
 12  generation     398 non-null    int64
 13  is_legendary   398 non-null    int64
dtypes: float64(2), int64(8), object(4)
memory usage: 43.7+ KB

In [9]:
df=df.drop('Unnamed: 0',axis=1)

In [10]:
df.head()

   against_water  attack capture_rate  ... weight_kg  generation  is_legendary
0            0.5      49           45  ...       6.9           1             0
1            0.5      62           45  ...      13.0           1             0
2            0.5     100           45  ...     100.0           1             0
3            2.0     104           45  ...      90.5           1             0
4            1.0      45           45  ...      32.0           1             0

[5 rows x 13 columns]

In [12]:
le=LabelEncoder()
df['type1']=le.fit_transform(df['type1'])
df['type2']=le.fit_transform(df['type2'])
df['classfication']=le.fit_transform(df['classfication'])

In [14]:
x=df.drop('is_legendary', axis=1)
y=df['is_legendary']

In [16]:
df.head()

   against_water  attack capture_rate  ...  weight_kg  generation  is_legendary
0            0.5      49           45  ...        6.9           1             0
1            0.5      62           45  ...       13.0           1             0
2            0.5     100           45  ...      100.0           1             0
3            2.0     104           45  ...       90.5           1             0
4            1.0      45           45  ...       32.0           1             0

[5 rows x 13 columns]

In [17]:
x['capture_rate'] = x['capture_rate'].astype(str).str.extract('(\\d+)').astype(float)
x['capture_rate'] = x['capture_rate'].fillna(x['capture_rate'].mean())
x=StandardScaler().fit_transform(x)

In [19]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=42)